<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.shipshuk.api.rest.bb</groupId>
    <artifactId>bb-rest-api</artifactId>
    <version>1.0</version>
    <packaging>war</packaging>
    <name>bb-rest-api-1.0</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jakartaee>11.0.0-M1</jakartaee>
    </properties>

    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>${jakartaee}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.shipshuk.log.client</groupId>
            <artifactId>jax-log-client</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.framework</groupId>
            <artifactId>jax-framework</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.lib.params</groupId>
            <artifactId>jax-lib-params</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.lib.session</groupId>
            <artifactId>jax-lib-session</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.lib.ftp.misc</groupId>
            <artifactId>jax-lib-ftp-misc</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.lib.antivirus</groupId>
            <artifactId>jax-lib-antivirus</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.lib.util</groupId>
            <artifactId>jax-lib-util</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.lib.persistence</groupId>
            <artifactId>jax-persistence</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.entity</groupId>
            <artifactId>SHIPSHUK_DB</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.wapi.geo</groupId>
            <artifactId>ss-wapi-geo</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.wapi.security</groupId>
            <artifactId>ss-wapi-security</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.wapi.catalog</groupId>
            <artifactId>ss-wapi-catalog</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.wapi.signup</groupId>
            <artifactId>ss-wapi-signup</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.wapi.ui</groupId>
            <artifactId>ss-wapi-ui</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.lib.common</groupId>
            <artifactId>ss-lib-common</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.worker.interfaces</groupId>
            <artifactId>jax-interfaces-worker</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.shipshuk.bb.lib.api</groupId>
            <artifactId>bb-lib-api</artifactId>
            <version>1.0</version>
        </dependency>

        <!-- EXTERNAL -->
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>3.1.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>6.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-fileupload2-jakarta-servlet6</artifactId>
            <version>2.0.0-M5</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-fileupload2-core</artifactId>
            <version>2.0.0-M5</version>
        </dependency>
        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>2.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client-gson</artifactId>
            <version>1.44.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client-jackson2</artifactId>
            <version>1.44.1</version>
        </dependency>
        

    </dependencies>
    
    <build>
        <finalName>bb-rest-api</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.12.1</version>
                <configuration>
                    <source>26</source>
                    <target>26</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
            </plugin>
        </plugins>
    </build>
</project>